/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passwordvault;

import java.awt.CardLayout;

/**
 *
 * @author Brian Sumner et al.
 */
public class PasswordVaultUI extends javax.swing.JFrame {

    
    // DEBUG MODE:  CHOOSE ONE OF THE FOLLOWING
    static boolean ENABLE_DEBUG = true;
//  static boolean ENABLE_DEBUG = false;

    
    
    
    /**
     * Creates new form PasswordVaultUI
     */
    public PasswordVaultUI() {
        debugMsg("INITIALIZING UI COMPONENTS");
        initComponents();
    }


    public static void debugMsg(String msg) {
        if (ENABLE_DEBUG)
            System.out.println("DEBUG:  " + msg);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelLoad = new javax.swing.JPanel();
        jPanelLoadButtons = new javax.swing.JPanel();
        jButtonLoadExit = new javax.swing.JButton();
        jButtonLoadNew = new javax.swing.JButton();
        jButtonLoadOpen = new javax.swing.JButton();
        jButtonLoadSubmit = new javax.swing.JButton();
        jPanelLoadText = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldVaultName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        panelAuth = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelFail = new javax.swing.JPanel();
        jLabelFailReason = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuVault = new javax.swing.JMenu();
        jMenuItemVaultLoad = new javax.swing.JMenuItem();
        jMenuItemVaultClose = new javax.swing.JMenuItem();
        jSeparatorVault1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemVaultExit = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        if (ENABLE_DEBUG) {
            jMenuDebug = new javax.swing.JMenu();
            jMenuDebugSelPanel = new javax.swing.JMenu();
            jMenuItemDebugSelPanelLoad = new javax.swing.JMenuItem();
            jMenuItemDebugSelPanelAuth = new javax.swing.JMenuItem();
            jMenuItemDebugSelPanelFail = new javax.swing.JMenuItem();

            setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    exitProgramEvent(evt);
                }
            });

            mainPanel.setLayout(new java.awt.CardLayout());

            jButtonLoadExit.setText("Exit");
            jButtonLoadExit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonLoadExitActionPerformed(evt);
                }
            });

            jButtonLoadNew.setText("Create New Vault");
            jButtonLoadNew.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonLoadNewActionPerformed(evt);
                }
            });

            jButtonLoadOpen.setText("Select Existing Vault");
            jButtonLoadOpen.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonLoadOpenActionPerformed(evt);
                }
            });

            jButtonLoadSubmit.setText("Submit");
            jButtonLoadSubmit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonLoadSubmitActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanelLoadButtonsLayout = new javax.swing.GroupLayout(jPanelLoadButtons);
            jPanelLoadButtons.setLayout(jPanelLoadButtonsLayout);
            jPanelLoadButtonsLayout.setHorizontalGroup(
                jPanelLoadButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLoadButtonsLayout.createSequentialGroup()
                    .addComponent(jButtonLoadExit)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonLoadNew)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonLoadOpen)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonLoadSubmit)
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            jPanelLoadButtonsLayout.setVerticalGroup(
                jPanelLoadButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLoadButtonsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelLoadButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonLoadExit)
                        .addComponent(jButtonLoadNew)
                        .addComponent(jButtonLoadOpen)
                        .addComponent(jButtonLoadSubmit))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jLabel1.setText("Vault Filename:");

            jTextFieldVaultName.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextFieldVaultNameActionPerformed(evt);
                }
            });

            jLabel4.setText("Vault Directory Path:");

            javax.swing.GroupLayout jPanelLoadTextLayout = new javax.swing.GroupLayout(jPanelLoadText);
            jPanelLoadText.setLayout(jPanelLoadTextLayout);
            jPanelLoadTextLayout.setHorizontalGroup(
                jPanelLoadTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTextFieldVaultName)
                .addComponent(jTextField1)
                .addGroup(jPanelLoadTextLayout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(jPanelLoadTextLayout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(307, 307, 307))
            );
            jPanelLoadTextLayout.setVerticalGroup(
                jPanelLoadTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLoadTextLayout.createSequentialGroup()
                    .addGroup(jPanelLoadTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldVaultName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            javax.swing.GroupLayout panelLoadLayout = new javax.swing.GroupLayout(panelLoad);
            panelLoad.setLayout(panelLoadLayout);
            panelLoadLayout.setHorizontalGroup(
                panelLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoadLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelLoadText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelLoadButtons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            panelLoadLayout.setVerticalGroup(
                panelLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoadLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelLoadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(jPanelLoadButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            mainPanel.add(panelLoad, "panelLoad");

            jLabel2.setText("auth");

            javax.swing.GroupLayout panelAuthLayout = new javax.swing.GroupLayout(panelAuth);
            panelAuth.setLayout(panelAuthLayout);
            panelAuthLayout.setHorizontalGroup(
                panelAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 406, Short.MAX_VALUE)
                .addGroup(panelAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAuthLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
            );
            panelAuthLayout.setVerticalGroup(
                panelAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 279, Short.MAX_VALUE)
                .addGroup(panelAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAuthLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
            );

            mainPanel.add(panelAuth, "panelAuth");

            jLabelFailReason.setText("...");

            jButton1.setText("OK");
            jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
            jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout panelFailLayout = new javax.swing.GroupLayout(panelFail);
            panelFail.setLayout(panelFailLayout);
            panelFailLayout.setHorizontalGroup(
                panelFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFailLayout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(jButton1)
                    .addContainerGap(180, Short.MAX_VALUE))
                .addGroup(panelFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFailLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelFailReason)
                        .addGap(0, 0, Short.MAX_VALUE)))
            );
            panelFailLayout.setVerticalGroup(
                panelFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFailLayout.createSequentialGroup()
                    .addContainerGap(158, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(98, 98, 98))
                .addGroup(panelFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFailLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelFailReason)
                        .addGap(0, 0, Short.MAX_VALUE)))
            );

            mainPanel.add(panelFail, "panelFail");

            jMenuVault.setText("Vault");

            jMenuItemVaultLoad.setText("Open Vault");
            jMenuVault.add(jMenuItemVaultLoad);

            jMenuItemVaultClose.setText("Close Vault");
            jMenuItemVaultClose.setEnabled(false);
            jMenuItemVaultClose.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemVaultCloseActionPerformed(evt);
                }
            });
            jMenuVault.add(jMenuItemVaultClose);
            jMenuVault.add(jSeparatorVault1);

            jMenuItemVaultExit.setText("Exit");
            jMenuItemVaultExit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemVaultExitActionPerformed(evt);
                }
            });
            jMenuVault.add(jMenuItemVaultExit);

            jMenuBar.add(jMenuVault);

            jMenuAbout.setText("About");
            jMenuBar.add(jMenuAbout);

            jMenuDebug.setText("DEBUG");

            jMenuDebugSelPanel.setText("SELECT PANEL");

            jMenuItemDebugSelPanelLoad.setText("panelLoad");
            jMenuItemDebugSelPanelLoad.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemDebugSelPanelLoadActionPerformed(evt);
                }
            });
            jMenuDebugSelPanel.add(jMenuItemDebugSelPanelLoad);

            jMenuItemDebugSelPanelAuth.setText("panelAuth");
            jMenuItemDebugSelPanelAuth.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemDebugSelPanelAuthActionPerformed(evt);
                }
            });
            jMenuDebugSelPanel.add(jMenuItemDebugSelPanelAuth);

            jMenuItemDebugSelPanelFail.setText("panelFail");
            jMenuItemDebugSelPanelFail.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemDebugSelPanelFailActionPerformed(evt);
                }
            });
            jMenuDebugSelPanel.add(jMenuItemDebugSelPanelFail);

            jMenuDebug.add(jMenuDebugSelPanel);

            jMenuBar.add(jMenuDebug);
        }

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDebugSelPanelLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDebugSelPanelLoadActionPerformed
        // TODO add your handling code here:
        changeCard("panelLoad");
    }//GEN-LAST:event_jMenuItemDebugSelPanelLoadActionPerformed

    private void jMenuItemDebugSelPanelAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDebugSelPanelAuthActionPerformed
        // TODO add your handling code here:
        changeCard("panelAuth");
    }//GEN-LAST:event_jMenuItemDebugSelPanelAuthActionPerformed

    private void jMenuItemVaultExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVaultExitActionPerformed
        // TODO add your handling code here:
        debugMsg("EXITING FROM MENU ITEM");
        exitProgram();
    }//GEN-LAST:event_jMenuItemVaultExitActionPerformed

    private void exitProgramEvent(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitProgramEvent
        // TODO add your handling code here:
        debugMsg("EXITING FROM WINDOW EVENT");
        exitProgram();
    }//GEN-LAST:event_exitProgramEvent

    private void jButtonLoadExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadExitActionPerformed
        // TODO add your handling code here:
        debugMsg("EXITING FROM LOAD PANEL BUTTON");
        exitProgram();

    }//GEN-LAST:event_jButtonLoadExitActionPerformed

    private void jButtonLoadNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoadNewActionPerformed

    private void jButtonLoadOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoadOpenActionPerformed

    private void jButtonLoadSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadSubmitActionPerformed
        // TODO add your handling code here:
        if (successOrFail("panelLoad", "")) {
            changeCard("panelAuth");
            jMenuItemVaultLoad.setEnabled(false);
            jMenuItemVaultClose.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonLoadSubmitActionPerformed

    private void jTextFieldVaultNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVaultNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVaultNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        changeCard(goBackToCard);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemDebugSelPanelFailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDebugSelPanelFailActionPerformed
        // TODO add your handling code here:
        changeCard("panelFail");
    }//GEN-LAST:event_jMenuItemDebugSelPanelFailActionPerformed

    private void jMenuItemVaultCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVaultCloseActionPerformed
        // TODO add your handling code here:
        changeCard("panelLoad");
    }//GEN-LAST:event_jMenuItemVaultCloseActionPerformed

    
    private void changeCard(String cardName) {
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, cardName);
        debugMsg("CHANGING TO CARD:  " + cardName);
    }
    
    
    private void showFailure(String reason, String goBackTo) {
        jLabelFailReason.setText(reason);
        goBackToCard = goBackTo;
        changeCard("panelFail");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordVaultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordVaultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordVaultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordVaultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordVaultUI().setVisible(true);
//                PasswordVault pwv = new PasswordVault();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLoadExit;
    private javax.swing.JButton jButtonLoadNew;
    private javax.swing.JButton jButtonLoadOpen;
    private javax.swing.JButton jButtonLoadSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFailReason;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuDebug;
    private javax.swing.JMenu jMenuDebugSelPanel;
    private javax.swing.JMenuItem jMenuItemDebugSelPanelAuth;
    private javax.swing.JMenuItem jMenuItemDebugSelPanelFail;
    private javax.swing.JMenuItem jMenuItemDebugSelPanelLoad;
    private javax.swing.JMenuItem jMenuItemVaultClose;
    private javax.swing.JMenuItem jMenuItemVaultExit;
    private javax.swing.JMenuItem jMenuItemVaultLoad;
    private javax.swing.JMenu jMenuVault;
    private javax.swing.JPanel jPanelLoadButtons;
    private javax.swing.JPanel jPanelLoadText;
    private javax.swing.JPopupMenu.Separator jSeparatorVault1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldVaultName;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelAuth;
    private javax.swing.JPanel panelFail;
    private javax.swing.JPanel panelLoad;
    // End of variables declaration//GEN-END:variables

    // CUSTOM VARS
    private String goBackToCard = "panelLoad";

        
    private boolean successOrFail(String originator, String args)
    {
        // INIT RESULT
        boolean result = false;
        String reason = "ERROR...";

        // NOTE: SWITCH OVER STRING NOT UNIVERSALLY COMPATIBLE
        // USE IF/ELSE INSTEAD
        if (originator.equals("panelLoad")) {
            debugMsg("RAN SOF FOR MODE:  LOAD");
            result = true;
//            showFailure(reason, originator);
        }
        else if (originator.equals("panelAuth")) {
            debugMsg("RAN SOF FOR MODE:  AUTH");
            result = true;
        }
        else {
            debugMsg("RAN SOF FOR MODE:  INVALID MODE");
            showFailure(reason, originator);
        }

        // RETURN RESULT
        return result;
    }

    
    private void exitProgram() {
        debugMsg("PROGRAM EXECUTION TERMINATED");
        System.exit(0);
    }
}