/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passwordvault;


import java.awt.CardLayout;
import java.io.File;
import javax.swing.JFileChooser;
import static passwordvault.Debug.debugMsg;
import static passwordvault.security.Hashing.getStrHash;
import static passwordvault.security.Hashing.getFileHash;


/**
 *
 * @author Brian Sumner et al.
 */
public class PasswordVaultUI extends javax.swing.JFrame {

    
    /**
     * Creates new form PasswordVaultUI
     */
    public PasswordVaultUI() {
        debugMsg("INITIALIZING UI COMPONENTS");
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        mainPanel = new javax.swing.JPanel();
        panelLoad = new javax.swing.JPanel();
        jPanelLoadButtons = new javax.swing.JPanel();
        jButtonLoadExit = new javax.swing.JButton();
        jButtonLoadNew = new javax.swing.JButton();
        jButtonLoadOpen = new javax.swing.JButton();
        jButtonLoadSubmit = new javax.swing.JButton();
        jPanelLoadText = new javax.swing.JPanel();
        jTextFieldLoadTextName = new javax.swing.JTextField();
        jLabelLoadTextPath = new javax.swing.JLabel();
        jTextFieldLoadTextPath = new javax.swing.JTextField();
        jLabelLoadTextName = new javax.swing.JLabel();
        panelDEBUGMSG = new javax.swing.JPanel();
        jLabelDEBUGMSG1 = new javax.swing.JLabel();
        jLabelDEBUGMSG2 = new javax.swing.JLabel();
        jLabelDEBUGMSG3 = new javax.swing.JLabel();
        jLabelDEBUGMSG4 = new javax.swing.JLabel();
        jLabelDEBUGMSG5 = new javax.swing.JLabel();
        jLabelDEBUGMSG6 = new javax.swing.JLabel();
        jLabelDEBUGMSG7 = new javax.swing.JLabel();
        jLabelDEBUGMSG8 = new javax.swing.JLabel();
        jLabelDEBUGMSG9 = new javax.swing.JLabel();
        jLabelDEBUGMSG10 = new javax.swing.JLabel();
        jPanelDEBUGMSGButtons = new javax.swing.JPanel();
        jButtonDEBUGMSG = new javax.swing.JButton();
        panelAuth = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordFieldAuthPW = new javax.swing.JPasswordField();
        jPanelAuthButtons = new javax.swing.JPanel();
        jButtonAuthCancel = new javax.swing.JButton();
        jButtonAuthChooseKeyfile = new javax.swing.JButton();
        jButtonAuthSubmit = new javax.swing.JButton();
        jLabelAuthKeyfilePath = new javax.swing.JLabel();
        jTextFieldAuthKeyfilePath = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        panelFail = new javax.swing.JPanel();
        jLabelFailReason = new javax.swing.JLabel();
        jButtonFail = new javax.swing.JButton();
        panelFeatured = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelStore = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelRetrieve = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemFileLoad = new javax.swing.JMenuItem();
        jMenuItemFileClose = new javax.swing.JMenuItem();
        jSeparatorMenuFile1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemFileSettings = new javax.swing.JMenuItem();
        jSeparatorMenuFile2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemFileExit = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemHelpHelp = new javax.swing.JMenuItem();
        jSeparatorMenuHelp1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemHelpAbout = new javax.swing.JMenuItem();
        jMenuDebug = new javax.swing.JMenu();
        jMenuDebugSelPanel = new javax.swing.JMenu();
        jMenuItemDebugSelPanelLoad = new javax.swing.JMenuItem();
        jMenuItemDebugSelPanelAuth = new javax.swing.JMenuItem();
        jMenuItemDebugSelPanelFail = new javax.swing.JMenuItem();
        jMenuItemDebugSelPanelFeatured = new javax.swing.JMenuItem();
        jMenuItemDebugSelPanelStore = new javax.swing.JMenuItem();
        jMenuItemDebugSelPanelRetrieve = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitProgramEvent(evt);
            }
        });

        mainPanel.setLayout(new java.awt.CardLayout());

        jButtonLoadExit.setText("Exit");
        jButtonLoadExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadExitActionPerformed(evt);
            }
        });

        jButtonLoadNew.setText("Create New Vault");
        jButtonLoadNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadNewActionPerformed(evt);
            }
        });

        jButtonLoadOpen.setText("Select Existing Vault");
        jButtonLoadOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadOpenActionPerformed(evt);
            }
        });

        jButtonLoadSubmit.setText("Submit");
        jButtonLoadSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoadButtonsLayout = new javax.swing.GroupLayout(jPanelLoadButtons);
        jPanelLoadButtons.setLayout(jPanelLoadButtonsLayout);
        jPanelLoadButtonsLayout.setHorizontalGroup(
            jPanelLoadButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoadButtonsLayout.createSequentialGroup()
                .addComponent(jButtonLoadExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLoadNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLoadOpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLoadSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLoadButtonsLayout.setVerticalGroup(
            jPanelLoadButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoadButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLoadButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLoadExit)
                    .addComponent(jButtonLoadNew)
                    .addComponent(jButtonLoadOpen)
                    .addComponent(jButtonLoadSubmit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextFieldLoadTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoadTextNameActionPerformed(evt);
            }
        });

        jLabelLoadTextPath.setText("Vault Directory Path:");

        javax.swing.GroupLayout jPanelLoadTextLayout = new javax.swing.GroupLayout(jPanelLoadText);
        jPanelLoadText.setLayout(jPanelLoadTextLayout);
        jPanelLoadTextLayout.setHorizontalGroup(
            jPanelLoadTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldLoadTextName)
            .addGroup(jPanelLoadTextLayout.createSequentialGroup()
                .addComponent(jLabelLoadTextPath)
                .addGap(0, 286, Short.MAX_VALUE))
            .addComponent(jTextFieldLoadTextPath)
        );
        jPanelLoadTextLayout.setVerticalGroup(
            jPanelLoadTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoadTextLayout.createSequentialGroup()
                .addComponent(jTextFieldLoadTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelLoadTextPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldLoadTextPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelLoadTextName.setText("Vault Filename:");

        javax.swing.GroupLayout panelLoadLayout = new javax.swing.GroupLayout(panelLoad);
        panelLoad.setLayout(panelLoadLayout);
        panelLoadLayout.setHorizontalGroup(
            panelLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLoadText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLoadButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLoadLayout.createSequentialGroup()
                        .addComponent(jLabelLoadTextName)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLoadLayout.setVerticalGroup(
            panelLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoadLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelLoadTextName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelLoadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(jPanelLoadButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(panelLoad, "panelLoad");

        jLabelDEBUGMSG1.setText("DEBUGMSG1");

        jLabelDEBUGMSG2.setText("DEBUGMSG2");

        jLabelDEBUGMSG3.setText("DEBUGMSG3");

        jLabelDEBUGMSG4.setText("DEBUGMSG4");

        jLabelDEBUGMSG5.setText("DEBUGMSG5");

        jLabelDEBUGMSG6.setText("DEBUGMSG6");

        jLabelDEBUGMSG7.setText("DEBUGMSG7");

        jLabelDEBUGMSG8.setText("DEBUGMSG8");

        jLabelDEBUGMSG9.setText("DEBUGMSG9");

        jLabelDEBUGMSG10.setText("DEBUGMSG10");

        jButtonDEBUGMSG.setText("Go Back");
        jButtonDEBUGMSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDEBUGMSGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDEBUGMSGButtonsLayout = new javax.swing.GroupLayout(jPanelDEBUGMSGButtons);
        jPanelDEBUGMSGButtons.setLayout(jPanelDEBUGMSGButtonsLayout);
        jPanelDEBUGMSGButtonsLayout.setHorizontalGroup(
            jPanelDEBUGMSGButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDEBUGMSGButtonsLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jButtonDEBUGMSG)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanelDEBUGMSGButtonsLayout.setVerticalGroup(
            jPanelDEBUGMSGButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDEBUGMSGButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDEBUGMSG)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelDEBUGMSGLayout = new javax.swing.GroupLayout(panelDEBUGMSG);
        panelDEBUGMSG.setLayout(panelDEBUGMSGLayout);
        panelDEBUGMSGLayout.setHorizontalGroup(
            panelDEBUGMSGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDEBUGMSGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDEBUGMSGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDEBUGMSG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDEBUGMSG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDEBUGMSG3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDEBUGMSG4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDEBUGMSG5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDEBUGMSG6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDEBUGMSG7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDEBUGMSG8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDEBUGMSG9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDEBUGMSG10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanelDEBUGMSGButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDEBUGMSGLayout.setVerticalGroup(
            panelDEBUGMSGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDEBUGMSGLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelDEBUGMSG1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDEBUGMSG2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDEBUGMSG3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDEBUGMSG4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDEBUGMSG5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDEBUGMSG6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDEBUGMSG7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDEBUGMSG8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDEBUGMSG9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDEBUGMSG10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jPanelDEBUGMSGButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(panelDEBUGMSG, "panelDEBUGMSG");

        jLabel2.setText("auth");

        jLabel5.setText("Enter Password:");

        jButtonAuthCancel.setText("Cancel");
        jButtonAuthCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAuthCancelActionPerformed(evt);
            }
        });

        jButtonAuthChooseKeyfile.setText("Choose Keyfile");
        jButtonAuthChooseKeyfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAuthChooseKeyfileActionPerformed(evt);
            }
        });

        jButtonAuthSubmit.setText("Submit");
        jButtonAuthSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAuthSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAuthButtonsLayout = new javax.swing.GroupLayout(jPanelAuthButtons);
        jPanelAuthButtons.setLayout(jPanelAuthButtonsLayout);
        jPanelAuthButtonsLayout.setHorizontalGroup(
            jPanelAuthButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAuthButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAuthCancel)
                .addGap(77, 77, 77)
                .addComponent(jButtonAuthChooseKeyfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButtonAuthSubmit)
                .addContainerGap())
        );
        jPanelAuthButtonsLayout.setVerticalGroup(
            jPanelAuthButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAuthButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAuthButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAuthSubmit)
                    .addComponent(jButtonAuthCancel)
                    .addComponent(jButtonAuthChooseKeyfile))
                .addContainerGap())
        );

        jLabelAuthKeyfilePath.setText("Keyfile Path:");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Use Keyfile for Two-Factor Authentication");
        jCheckBox1.setEnabled(false);

        javax.swing.GroupLayout panelAuthLayout = new javax.swing.GroupLayout(panelAuth);
        panelAuth.setLayout(panelAuthLayout);
        panelAuthLayout.setHorizontalGroup(
            panelAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAuthButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelAuthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordFieldAuthPW)
                    .addComponent(jTextFieldAuthKeyfilePath)
                    .addGroup(panelAuthLayout.createSequentialGroup()
                        .addGroup(panelAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabelAuthKeyfilePath))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAuthLayout.setVerticalGroup(
            panelAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAuthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldAuthPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelAuthKeyfilePath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAuthKeyfilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jPanelAuthButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(panelAuth, "panelAuth");

        jLabelFailReason.setText("...");

        jButtonFail.setText("Go Back");
        jButtonFail.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonFail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFailLayout = new javax.swing.GroupLayout(panelFail);
        panelFail.setLayout(panelFailLayout);
        panelFailLayout.setHorizontalGroup(
            panelFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFailLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jButtonFail)
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(panelFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFailLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelFailReason)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelFailLayout.setVerticalGroup(
            panelFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFailLayout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jButtonFail)
                .addGap(98, 98, 98))
            .addGroup(panelFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFailLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelFailReason)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainPanel.add(panelFail, "panelFail");

        jLabel1.setText("Featured Menu");

        javax.swing.GroupLayout panelFeaturedLayout = new javax.swing.GroupLayout(panelFeatured);
        panelFeatured.setLayout(panelFeaturedLayout);
        panelFeaturedLayout.setHorizontalGroup(
            panelFeaturedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(panelFeaturedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFeaturedLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelFeaturedLayout.setVerticalGroup(
            panelFeaturedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
            .addGroup(panelFeaturedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFeaturedLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainPanel.add(panelFeatured, "panelFeatured");

        jLabel3.setText("Store Data Menu");

        javax.swing.GroupLayout panelStoreLayout = new javax.swing.GroupLayout(panelStore);
        panelStore.setLayout(panelStoreLayout);
        panelStoreLayout.setHorizontalGroup(
            panelStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(panelStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStoreLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelStoreLayout.setVerticalGroup(
            panelStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
            .addGroup(panelStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelStoreLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainPanel.add(panelStore, "panelStore");

        jLabel4.setText("Retrieve Data Menu");

        javax.swing.GroupLayout panelRetrieveLayout = new javax.swing.GroupLayout(panelRetrieve);
        panelRetrieve.setLayout(panelRetrieveLayout);
        panelRetrieveLayout.setHorizontalGroup(
            panelRetrieveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(panelRetrieveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRetrieveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelRetrieveLayout.setVerticalGroup(
            panelRetrieveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
            .addGroup(panelRetrieveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRetrieveLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainPanel.add(panelRetrieve, "panelRetrieve");

        jMenuFile.setText("File");

        jMenuItemFileLoad.setText("Open Vault");
        jMenuItemFileLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileLoadActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileLoad);

        jMenuItemFileClose.setText("Close Vault");
        jMenuItemFileClose.setEnabled(false);
        jMenuItemFileClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileCloseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileClose);
        jMenuFile.add(jSeparatorMenuFile1);

        jMenuItemFileSettings.setText("Settings");
        jMenuItemFileSettings.setEnabled(false);
        jMenuFile.add(jMenuItemFileSettings);
        jMenuFile.add(jSeparatorMenuFile2);

        jMenuItemFileExit.setText("Exit");
        jMenuItemFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileExit);

        jMenuBar.add(jMenuFile);

        jMenuHelp.setText("Help");

        jMenuItemHelpHelp.setText("Help");
        jMenuHelp.add(jMenuItemHelpHelp);
        jMenuHelp.add(jSeparatorMenuHelp1);

        jMenuItemHelpAbout.setText("About");
        jMenuHelp.add(jMenuItemHelpAbout);

        jMenuBar.add(jMenuHelp);

        jMenuDebug.setText("DEBUG");

        jMenuDebugSelPanel.setText("SELECT PANEL");

        jMenuItemDebugSelPanelLoad.setText("panelLoad");
        jMenuItemDebugSelPanelLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDebugSelPanelLoadActionPerformed(evt);
            }
        });
        jMenuDebugSelPanel.add(jMenuItemDebugSelPanelLoad);

        jMenuItemDebugSelPanelAuth.setText("panelAuth");
        jMenuItemDebugSelPanelAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDebugSelPanelAuthActionPerformed(evt);
            }
        });
        jMenuDebugSelPanel.add(jMenuItemDebugSelPanelAuth);

        jMenuItemDebugSelPanelFail.setText("panelFail");
        jMenuItemDebugSelPanelFail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDebugSelPanelFailActionPerformed(evt);
            }
        });
        jMenuDebugSelPanel.add(jMenuItemDebugSelPanelFail);

        jMenuItemDebugSelPanelFeatured.setText("panelFeatured");
        jMenuItemDebugSelPanelFeatured.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDebugSelPanelFeaturedActionPerformed(evt);
            }
        });
        jMenuDebugSelPanel.add(jMenuItemDebugSelPanelFeatured);

        jMenuItemDebugSelPanelStore.setText("panelStore");
        jMenuItemDebugSelPanelStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDebugSelPanelStoreActionPerformed(evt);
            }
        });
        jMenuDebugSelPanel.add(jMenuItemDebugSelPanelStore);

        jMenuItemDebugSelPanelRetrieve.setText("panelRetrieve");
        jMenuItemDebugSelPanelRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDebugSelPanelRetrieveActionPerformed(evt);
            }
        });
        jMenuDebugSelPanel.add(jMenuItemDebugSelPanelRetrieve);

        jMenuDebug.add(jMenuDebugSelPanel);

        jMenuBar.add(jMenuDebug);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDebugSelPanelLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDebugSelPanelLoadActionPerformed
        // TODO add your handling code here:
        changeCard("panelLoad");
    }//GEN-LAST:event_jMenuItemDebugSelPanelLoadActionPerformed

    private void jMenuItemDebugSelPanelAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDebugSelPanelAuthActionPerformed
        // TODO add your handling code here:
        changeCard("panelAuth");
    }//GEN-LAST:event_jMenuItemDebugSelPanelAuthActionPerformed

    private void jMenuItemFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileExitActionPerformed
        // TODO add your handling code here:
        debugMsg("EXITING FROM MENU ITEM");
        exitProgram();
    }//GEN-LAST:event_jMenuItemFileExitActionPerformed

    private void exitProgramEvent(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitProgramEvent
        // TODO add your handling code here:
        debugMsg("EXITING FROM WINDOW EVENT");
        exitProgram();
    }//GEN-LAST:event_exitProgramEvent

    private void jButtonLoadExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadExitActionPerformed
        // TODO add your handling code here:
        debugMsg("EXITING FROM panelLoad EXIT BUTTON");
        exitProgram();
    }//GEN-LAST:event_jButtonLoadExitActionPerformed

    private void jButtonLoadNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadNewActionPerformed
        // TODO add your handling code here:
        debugMsg("panelLoad:  CREATE NEW VAULT BUTTON PRESSED");
    }//GEN-LAST:event_jButtonLoadNewActionPerformed

    private void jButtonLoadOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadOpenActionPerformed
        // TODO add your handling code here:
        debugMsg("panelLoad:  OPEN EXISTING VAULT BUTTON PRESSED");
    }//GEN-LAST:event_jButtonLoadOpenActionPerformed

    private void jButtonLoadSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadSubmitActionPerformed
        // TODO add your handling code here:
        if (isSuccessful("panelLoad", "")) {
            changeCard("panelAuth");
            jMenuItemFileLoad.setEnabled(false);
            jMenuItemFileClose.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonLoadSubmitActionPerformed

    private void jTextFieldLoadTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoadTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoadTextNameActionPerformed

    private void jButtonFailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFailActionPerformed
        // TODO add your handling code here:
        debugMsg("FAILURE ACCEPTED");
        changeCard(goBackToCard);
    }//GEN-LAST:event_jButtonFailActionPerformed

    private void jMenuItemDebugSelPanelFailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDebugSelPanelFailActionPerformed
        // TODO add your handling code here:
        changeCard("panelFail");
    }//GEN-LAST:event_jMenuItemDebugSelPanelFailActionPerformed

    private void jMenuItemFileCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileCloseActionPerformed
        debugMsg("CLOSING VAULT FROM MENU ITEM");
            jMenuItemFileLoad.setEnabled(true);
            jMenuItemFileClose.setEnabled(false);
        changeCard("panelLoad");
    }//GEN-LAST:event_jMenuItemFileCloseActionPerformed

    private void jMenuItemDebugSelPanelFeaturedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDebugSelPanelFeaturedActionPerformed
        // TODO add your handling code here:
        changeCard("panelFeatured");
    }//GEN-LAST:event_jMenuItemDebugSelPanelFeaturedActionPerformed

    private void jMenuItemDebugSelPanelStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDebugSelPanelStoreActionPerformed
        // TODO add your handling code here:
        changeCard("panelStore");
    }//GEN-LAST:event_jMenuItemDebugSelPanelStoreActionPerformed

    private void jMenuItemDebugSelPanelRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDebugSelPanelRetrieveActionPerformed
        // TODO add your handling code here:
        changeCard("panelRetrieve");
    }//GEN-LAST:event_jMenuItemDebugSelPanelRetrieveActionPerformed

    private void jButtonAuthSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAuthSubmitActionPerformed
        // TODO add your handling code here:
        
        
        // DEBUG
        String tempPW = new String(jPasswordFieldAuthPW.getPassword());
        jLabelDEBUGMSG1.setText("*** PASSWORD INPUT = ***");
        jLabelDEBUGMSG2.setText(tempPW);
        jLabelDEBUGMSG3.setText("*** PASSWORD HASH = ***");
        jLabelDEBUGMSG4.setText(getStrHash(tempPW));
        jLabelDEBUGMSG5.setText("*** KEYFILE PATH = ***");
        jLabelDEBUGMSG6.setText(keyFilePath);
        jLabelDEBUGMSG7.setText("*** KEYFILE HASH = ***");
        jLabelDEBUGMSG8.setText(getFileHash(keyFilePath));
        jLabelDEBUGMSG9.setText("*** COMBINED PASSWORD+KEYFILE REHASH = ***");
        jLabelDEBUGMSG10.setText(getStrHash(tempPW + getFileHash(keyFilePath)));
        
        goBackToCard = "panelAuth";
        changeCard("panelDEBUGMSG");
        tempPW = "";
    }//GEN-LAST:event_jButtonAuthSubmitActionPerformed

    private void jButtonDEBUGMSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDEBUGMSGActionPerformed
        // TODO add your handling code here:
        changeCard(goBackToCard);
        jLabelDEBUGMSG1.setText("DEBUGMSG1");
        jLabelDEBUGMSG2.setText("DEBUGMSG2");
        jLabelDEBUGMSG3.setText("DEBUGMSG3");
        jLabelDEBUGMSG4.setText("DEBUGMSG4");
        jLabelDEBUGMSG5.setText("DEBUGMSG5");
        jLabelDEBUGMSG6.setText("DEBUGMSG6");
        jLabelDEBUGMSG7.setText("DEBUGMSG7");
        jLabelDEBUGMSG8.setText("DEBUGMSG8");
        jLabelDEBUGMSG8.setText("DEBUGMSG9");
        jLabelDEBUGMSG8.setText("DEBUGMSG10");

    }//GEN-LAST:event_jButtonDEBUGMSGActionPerformed

    private void jButtonAuthCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAuthCancelActionPerformed
        debugMsg("panelAuth:  CANCELLING AUTHENTICATION");
        // RESET INPUTS
        jPasswordFieldAuthPW.setText("");
        // GO BACK TO LOAD
        changeCard("panelLoad");
    }//GEN-LAST:event_jButtonAuthCancelActionPerformed

    private void jMenuItemFileLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileLoadActionPerformed
        changeCard("panelLoad");
    }//GEN-LAST:event_jMenuItemFileLoadActionPerformed

    private void jButtonAuthChooseKeyfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAuthChooseKeyfileActionPerformed
        int returnVal = jFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
//            try {
//              // What to do with the file, e.g. display it in a TextArea
//              textarea.read( new FileReader( file.getAbsolutePath() ), null );
//            } catch (IOException ex) {
//              System.out.println("problem accessing file"+file.getAbsolutePath());
//            }
            debugMsg("SUCCESSFULLLY OPENED FILE");
            debugMsg("FILE DIRECTORY = " + jFileChooser.getCurrentDirectory());
            debugMsg("FILE NAME = " + jFileChooser.getName(file));
            debugMsg("FILE PATH = " + file.getAbsolutePath());
            keyFilePath = file.getAbsolutePath();
            jTextFieldAuthKeyfilePath.setText(keyFilePath);
        } else {
            debugMsg("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButtonAuthChooseKeyfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordVaultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordVaultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordVaultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordVaultUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordVaultUI().setVisible(true);
//                PasswordVault pwv = new PasswordVault();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAuthCancel;
    private javax.swing.JButton jButtonAuthChooseKeyfile;
    private javax.swing.JButton jButtonAuthSubmit;
    private javax.swing.JButton jButtonDEBUGMSG;
    private javax.swing.JButton jButtonFail;
    private javax.swing.JButton jButtonLoadExit;
    private javax.swing.JButton jButtonLoadNew;
    private javax.swing.JButton jButtonLoadOpen;
    private javax.swing.JButton jButtonLoadSubmit;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAuthKeyfilePath;
    private javax.swing.JLabel jLabelDEBUGMSG1;
    private javax.swing.JLabel jLabelDEBUGMSG10;
    private javax.swing.JLabel jLabelDEBUGMSG2;
    private javax.swing.JLabel jLabelDEBUGMSG3;
    private javax.swing.JLabel jLabelDEBUGMSG4;
    private javax.swing.JLabel jLabelDEBUGMSG5;
    private javax.swing.JLabel jLabelDEBUGMSG6;
    private javax.swing.JLabel jLabelDEBUGMSG7;
    private javax.swing.JLabel jLabelDEBUGMSG8;
    private javax.swing.JLabel jLabelDEBUGMSG9;
    private javax.swing.JLabel jLabelFailReason;
    private javax.swing.JLabel jLabelLoadTextName;
    private javax.swing.JLabel jLabelLoadTextPath;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuDebug;
    private javax.swing.JMenu jMenuDebugSelPanel;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemDebugSelPanelAuth;
    private javax.swing.JMenuItem jMenuItemDebugSelPanelFail;
    private javax.swing.JMenuItem jMenuItemDebugSelPanelFeatured;
    private javax.swing.JMenuItem jMenuItemDebugSelPanelLoad;
    private javax.swing.JMenuItem jMenuItemDebugSelPanelRetrieve;
    private javax.swing.JMenuItem jMenuItemDebugSelPanelStore;
    private javax.swing.JMenuItem jMenuItemFileClose;
    private javax.swing.JMenuItem jMenuItemFileExit;
    private javax.swing.JMenuItem jMenuItemFileLoad;
    private javax.swing.JMenuItem jMenuItemFileSettings;
    private javax.swing.JMenuItem jMenuItemHelpAbout;
    private javax.swing.JMenuItem jMenuItemHelpHelp;
    private javax.swing.JPanel jPanelAuthButtons;
    private javax.swing.JPanel jPanelDEBUGMSGButtons;
    private javax.swing.JPanel jPanelLoadButtons;
    private javax.swing.JPanel jPanelLoadText;
    private javax.swing.JPasswordField jPasswordFieldAuthPW;
    private javax.swing.JPopupMenu.Separator jSeparatorMenuFile1;
    private javax.swing.JPopupMenu.Separator jSeparatorMenuFile2;
    private javax.swing.JPopupMenu.Separator jSeparatorMenuHelp1;
    private javax.swing.JTextField jTextFieldAuthKeyfilePath;
    private javax.swing.JTextField jTextFieldLoadTextName;
    private javax.swing.JTextField jTextFieldLoadTextPath;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelAuth;
    private javax.swing.JPanel panelDEBUGMSG;
    private javax.swing.JPanel panelFail;
    private javax.swing.JPanel panelFeatured;
    private javax.swing.JPanel panelLoad;
    private javax.swing.JPanel panelRetrieve;
    private javax.swing.JPanel panelStore;
    // End of variables declaration//GEN-END:variables

    // CUSTOM VARS
    private String goBackToCard = "panelLoad";
    private String keyFilePath = "";

    
    // CHANGES CARD IN mainPanel TO cardName   
    private void changeCard(String cardName) {
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, cardName);
        debugMsg("CHANGING TO CARD:  " + cardName);
    }
    
    
    // DISPLAYS CUSTOM ERROR MESSAGE WITH BACK BUTTON
    private void showFailure(String reason, String goBackTo) {
        jLabelFailReason.setText(reason);
        goBackToCard = goBackTo;
        changeCard("panelFail");
        
    }
    
    // 
    private boolean isSuccessful(String caller, String args)
    {

        debugMsg("RAN SOF FROM:  " + caller);


        // INIT RESULT
        boolean result = false;
        String reason = "ERROR...";

        // NOTE: SWITCH OVER STRING NOT UNIVERSALLY COMPATIBLE
        // USE IF/ELSE INSTEAD
        if (caller.equals("panelLoad")) {
            debugMsg(caller + ":  SUBMITTED VAULT NAME:  " + jTextFieldLoadTextName.getText());
            debugMsg(caller + ":  SUBMITTED VAULT PATH:  " + jTextFieldLoadTextPath.getText());

            result = true;
//            showFailure(reason, originator);
        }
        else if (caller.equals("panelAuth")) {
            result = true;
        }
        else {
            showFailure(reason, caller);
        }

        // RETURN RESULT
        return result;
    }

    
    
    
    private void exitProgram() {
        debugMsg("PROGRAM EXECUTION TERMINATED");
        System.exit(0);
    }
}